library(baydem)

# Clear the workspace
rm(list=ls())

# Simulation results are created by calling, in turn, the following two scripts:
#
# (1) do_simulations.R
# (2) create_simulation_plots.R [this script]
#
# create_simulation_plots.R uses the results generated by the preceding script,
# do_simulations.R, to make publication plots.

# ------------------------------------------------------------------------------
# (0) Define a function used below
# ------------------------------------------------------------------------------

# Load the result of a KDE fit done externally using the OxCal web inteface.
load_KDE_Plot_fit <- function(file_name) {
  data_frame <- read.table(file_name,sep="\t")
  tau <- as.vector(data_frame[,1])
  f   <- as.vector(data_frame[,2])
  dtau <- unique(diff(tau))
  if (length(dtau) != 1) {
    stop("Spacing of tau is not even")
  }
  f <- f/sum(f)/dtau
  return(list(tau=tau,f=f))
}

# ------------------------------------------------------------------------------
# (1) Load the data for the two plots, Fig2_non_bayesian_fits.pdf and
# Fig3_bayesian_fits.pdf.
#
# The non-Bayesian fits are:
# (a) The target density (known simulation density)
# (b) The maximum likelihood fit
# (c) The summed density
# (d) A Bchron mixture fit
# (e) An OxCal KDE (for N=100 and N=1000)
#
# ------------------------------------------------------------------------------

# Load the simulation
sim_file <- file.path("outputs","sim10000.rds")
if (!file.exists(sim_file)) {
  stop("Missing simulation save file")
}
sim10000 <- readRDS(sim_file)
th_sim  <- sim10000$sim_spec$model_spec$th[1:6]
tau_min <- sim10000$sim_spec$model_spec$th[7]
tau_max <- sim10000$sim_spec$model_spec$th[8]
calib_curve <- sim10000$sim_spec$calib_curve
calib_df <- load_calib_curve(calib_curve)

# Load hp and density_model
if (!file.exists(file.path("outputs","hp.rds"))) {
  stop("hp.rds not found")
} else {
  hp <- readRDS(file.path("outputs","hp.rds"))
}
dtau <- hp$dtau
tau_plot <- seq(tau_min,tau_max,by=dtau)

if (!file.exists(file.path("outputs","density_model.rds"))) {
  stop("density_model.rds not found")
} else {
  density_model <- readRDS(file.path("outputs","density_model.rds"))
}

# Load the maximum likelihood fits
Nvect <- c(100,1000,10000)
max_lik_fit_list <- list()
for(m_N in 1:length(Nvect)) {
  N <- Nvect[m_N]
  save_file <- file.path("outputs",paste0("max_lik_fit",N,".rds"))
  if (!file.exists(save_file)) {
    stop(paste0("File not found: ", save_file))
  } else {
    max_lik_fit_list[[m_N]] <- readRDS(save_file)
  }
}
f_ml100 <- calc_gauss_mix_pdf(max_lik_fit_list[[1]]$th,
                              tau_plot,
                              tau_min=tau_min,
                              tau_max=tau_max)
f_ml1000 <- calc_gauss_mix_pdf(max_lik_fit_list[[2]]$th,
                               tau_plot,
                               tau_min=tau_min,
                               tau_max=tau_max)
f_ml10000 <- calc_gauss_mix_pdf(max_lik_fit_list[[3]]$th,
                                tau_plot,
                                tau_min=tau_min,
                                tau_max=tau_max)

# Load the KDE fits (only have two, for N=100 and N=1000)
kde_fit_list <- list()
num_kde_fits <- 2
for(m_N in 1:num_kde_fits) {
  N <- Nvect[m_N]
  save_file <- file.path("outputs",paste0("posterior_from_oxcal_",N,".txt"))
  if (!file.exists(save_file)) {
    stop(paste0("File not found: ", save_file))
  } else {
    kde_fit_list[[m_N]] <- load_KDE_Plot_fit(save_file)
  }
}
kde100  <- kde_fit_list[[1]]
kde1000 <- kde_fit_list[[2]]

# Load the Bayesian inference files (solutions)
bayesian_soln_list <- list()
for(m_N in 1:length(Nvect)) {
  N <- Nvect[m_N]
  save_file <- file.path("outputs",paste0("bayesian_soln",N,".rds"))
  if (!file.exists(save_file)) {
    stop(paste0("File not found: ", save_file))
  } else {
    bayesian_soln_list[[m_N]] <- readRDS(save_file)
  }
}

# Load the Bayesian summaries
bayesian_summ_list <- list()
for(m_N in 1:length(Nvect)) {
  N <- Nvect[m_N]
  save_file <- file.path("outputs",paste0("bayesian_summ",N,".rds"))
  if (!file.exists(save_file)) {
    stop(paste0("File not found: ", save_file))
  } else {
    bayesian_summ_list[[m_N]] <- readRDS(save_file)
  }
}

# Load the Bchron fits
bchron_fit_list <- list()
for(m_N in 1:length(Nvect)) {
  N <- Nvect[m_N]
  save_file <- file.path("outputs",paste0("bchron_fit",N,".rds"))
  if (!file.exists(save_file)) {
    stop(paste0("File not found: ", save_file))
  } else {
    bchron_fit_list[[m_N]] <- readRDS(save_file)
  }
}
bchron100   <- bchron_fit_list[[1]]
bchron1000  <- bchron_fit_list[[2]]
bchron10000 <- bchron_fit_list[[3]]

# Create the known target density and summed densities for each simulation
f_sim <- calc_gauss_mix_pdf(th_sim,tau_plot,tau_min=tau_min,tau_max=tau_max)

M100 <- calc_meas_matrix(tau_plot,
                         sim10000$data$rc_meas$phi_m[1:100],
                         sim10000$data$rc_meas$sig_m[1:100],
                         calib_df
                         )
M100 <- M100 / replicate(length(tau_plot),rowSums(M100)*dtau)
f_spdf100 <- colMeans(M100)

M1000 <- calc_meas_matrix(tau_plot,
                          sim10000$data$rc_meas$phi_m[1:1000],
                          sim10000$data$rc_meas$sig_m[1:1000],
                          calib_df
                          )
M1000 <- M1000 / replicate(length(tau_plot),rowSums(M1000)*dtau)
f_spdf1000 <- colMeans(M1000)

M10000 <- calc_meas_matrix(tau_plot,
                           sim10000$data$rc_meas$phi_m,
                           sim10000$data$rc_meas$sig_m,
                           calib_df
                           )
M10000 <- M10000 / replicate(length(tau_plot),rowSums(M10000)*dtau)
f_spdf10000 <- colMeans(M10000)
# ------------------------------------------------------------------------------
# (2) Make Fig2_non_bayesian_fits.pdf
# ------------------------------------------------------------------------------
num_plots <- 3
pdf(file.path("outputs","Fig2_non_bayesian_fits.pdf"),
    width=5,height=2.5*num_plots)

  par(
    mfrow = c(num_plots, 1),
    xaxs = "i", # No padding for x-axis
    yaxs = "i", # No padding for y-axis
    # outer margins with ordering bottom, left, top, right:
    oma = c(4, 2, 2, 2),
    # plot margins with ordering bottom, left, top, right:
    mar = c(2, 4, 0, 0)
  )

  # N=100
  plot(tau_plot,
       f_sim,
       xlim=c(tau_min,tau_max),
       ylim=c(0,0.01),
       xlab = "",
       ylab = "Density",
       xaxt = "n",
       yaxt = "n",
       col="blue",
       type="l",
       lwd=2
      )
  lines(tau_plot,f_spdf100,col="black",lwd=2)
  lines(tau_plot,f_ml100,col="red",lwd=2)
  lines(kde100$tau,kde100$f,col="grey",lwd=2)
  lines(bchron100$tau,bchron100$f,col="grey",lwd=2,lty=3)
  # Add a label inicating the value of N
  text(
    labels = "N = 100",
    x = 600,
    y = 0.009,
    pos = 4,
    cex = 2
  )
  # Add a legend (only to the top plot)
  legend("topright",
       legend = c("Target","Max. Lik.","SPD","Bchron Mix.","OxCal KDE"),
       lty = c(1,1,1,3,1),
       col = c("Blue","Red","Black","Grey","Grey"),
       lwd = 2)

  # N=1000
  plot(tau_plot,
       f_sim,
       xlim=c(tau_min,tau_max),
       ylim=c(0,0.01),
       xlab = "",
       ylab = "Density",
       xaxt = "n",
       yaxt = "n",
       col="blue",
       type="l",
       lwd=2
      )
  lines(tau_plot,f_spdf1000,col="black",lwd=2)
  lines(tau_plot,f_ml1000,col="red",lwd=2)
  lines(kde1000$tau,kde1000$f,col="grey",lwd=2)
  lines(bchron1000$tau,bchron1000$f,col="grey",lwd=2,lty=3)
  # Add a label inicating the value of N
  text(
    labels = "N = 1000",
    x = 600,
    y = 0.009,
    pos = 4,
    cex = 2
  )

  # N=10000
  plot(tau_plot,
       f_sim,
       xlim=c(tau_min,tau_max),
       ylim=c(0,0.01),
       xlab = "",
       ylab = "Density",
       xaxt = "n",
       yaxt = "n",
       col="blue",
       type="l",
       lwd=2
      )
  lines(tau_plot,f_spdf10000,col="black",lwd=2)
  lines(tau_plot,f_ml10000,col="red",lwd=2)
  lines(bchron10000$tau,bchron10000$f,col="grey",lwd=2,lty=3)
  # Add a label inicating the value of N
  text(
    labels = "N = 10000",
    x = 600,
    y = 0.009,
    pos = 4,
    cex = 2
  )

  axis(side = 1)
  mtext("Calendar Date [AD]", side = 1, line = 2.5, cex = 0.75)

dev.off()

# ------------------------------------------------------------------------------
# (3) Make Fig3_bayesian_fits.pdf (this includes an initial sub-plot visualizing
# the calibratrion curve and three sub-plots showing Bayesian inference for each
# of N=100, N=1000, and N=10000.
# ------------------------------------------------------------------------------
num_plots <- 4
pdf(file.path("outputs","Fig3_bayesian_fits.pdf"),
    width=5,height=2.5*num_plots)

  par(
    mfrow = c(num_plots, 1),
    xaxs = "i", # No padding for x-axis
    yaxs = "i", # No padding for y-axis
    # outer margins with ordering bottom, left, top, right:
    oma = c(4, 2, 2, 2),
    # plot margins with ordering bottom, left, top, right:
    mar = c(2, 4, 0, 0)
  )

  # (1) Add the calibration curve (first plot)
  par(mar = c(0, 4, 0, 0))
  vis_calib_curve(
    tau_min,
    tau_max,
    calib_df,
    xlab = "",
    ylab = "Fraction Modern",
    xaxt = "n",
    invert_col = "gray80"
  )
  box()

  # N = 100
  # Make a blank plot
  make_blank_density_plot(bayesian_summ_list[[1]],
    ylim = c(0, 0.01),
    xlab = "",
    ylab = "Density",
    xaxt = "n",
    yaxt = "n"
  )

  # Add the shaded quantiles
  add_shaded_quantiles(bayesian_summ_list[[1]],
    col = "gray80"
  )

  # Add the summed probability density
  plot_summed_density(bayesian_summ_list[[1]],
    lwd = 2,
    add = T,
    col = "black"
  )

  # Add solid 50% quantile
  plot_50_percent_quantile(bayesian_summ_list[[1]],
    lwd = 2,
    add = T,
    col = "red"
  )

  # Plot the known, target distribution
  plot_known_sim_density(bayesian_summ_list[[1]],
    lwd = 2,
    add = T,
    col = "blue"
  )

  text(
    labels = "N = 100",
    x = 600,
    y = 0.009,
    pos = 4,
    cex = 2
  )

  # N = 1000
  # Make a blank plot
  make_blank_density_plot(bayesian_summ_list[[2]],
    ylim = c(0, 0.01),
    xlab = "",
    ylab = "Density",
    xaxt = "n",
    yaxt = "n"
  )

  # Add the shaded quantiles
  add_shaded_quantiles(bayesian_summ_list[[2]],
    col = "gray80"
  )

  # Add the summed probability density
  plot_summed_density(bayesian_summ_list[[2]],
    lwd = 2,
    add = T,
    col = "black"
  )

  # Add solid 50% quantile
  plot_50_percent_quantile(bayesian_summ_list[[2]],
    lwd = 2,
    add = T,
    col = "red"
  )

  # Plot the known, target distribution
  plot_known_sim_density(bayesian_summ_list[[2]],
    lwd = 2,
    add = T,
    col = "blue"
  )

  text(
    labels = "N = 1000",
    x = 600,
    y = 0.009,
    pos = 4,
    cex = 2
  )

  # N = 10000
  # Make a blank plot
  make_blank_density_plot(bayesian_summ_list[[3]],
    ylim = c(0, 0.01),
    xlab = "",
    ylab = "Density",
    xaxt = "n",
    yaxt = "n"
  )

  # Add the shaded quantiles
  add_shaded_quantiles(bayesian_summ_list[[3]],
    col = "gray80"
  )

  # Add the summed probability density
  plot_summed_density(bayesian_summ_list[[3]],
    lwd = 2,
    add = T,
    col = "black"
  )

  # Add solid 50% quantile
  plot_50_percent_quantile(bayesian_summ_list[[3]],
    lwd = 2,
    add = T,
    col = "red"
  )

  # Plot the known, target distribution
  plot_known_sim_density(bayesian_summ_list[[3]],
    lwd = 2,
    add = T,
    col = "blue"
  )

  text(
    labels = "N = 1000",
    x = 600,
    y = 0.009,
    pos = 4,
    cex = 2
  )

  # Add an axis and label to the final, bottom plot
  axis(side = 1)
  mtext("Calendar Date [AD]", side = 1, line = 2.5, cex = 0.75)
dev.off()