---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
# Please put your title here to include it in the file below.
Title <- "End-to-end Bayesian analysis for summarizing sets of radiocarbon dates"
```

# price_et_al_tikal_rc

This repository contains the data and code for our paper:

> Price, M.H., J.M. Capriles, J. Hoggarth, R.K. Bocinsky, C.E. Ebert, and J.H. Jones, (2020). _`r Title`_. In review.

<!-- Our pre-print is online here: -->

<!-- > Authors, (YYYY). _`r Title`_. Name of journal/book, Accessed `r format(Sys.Date(), "%d %b %Y")`. Online at <https://doi.org/xxx/xxx> -->


### How to cite

Please cite this compendium as:

> Price, M.H., J.M. Capriles, J. Hoggarth, R.K. Bocinsky, C.E. Ebert, and J.H. Jones, (`r format(Sys.Date(), "%Y")`). _Compendium of R code and data for `r Title`_. Accessed `r format(Sys.Date(), "%d %b %Y")`.


## Getting the code and input data
The easiest way to get the code and input data is to clone this github repository. For example, enter the following at the command line to clone the repository, enter the newly-created directory, and list its contents:

```console
git clone https://github.com/MichaelHoltonPrice/price_et_al_tikal_rc
cd price_et_al_tikal_rc
ls
```

## Requirements
This research compendium has been developed using the statistical
programming language R. To work with the compendium, you will need
the [R
software](https://cloud.r-project.org/) itself and optionally [RStudio
Desktop](https://rstudio.com/products/rstudio/download/).


To install the R packages that the code depends on enter the following in *R*:

``` r
# If necessary, install devtools
install.packages("devtools")

# Install baydem. On Linux, this may first require running the following in a terminal window:
# sudo apt-get install libv8-dev
devtools::install_github('eehh-stanford/baydem')

# If necessary, install additional package dependencies:
install.packages('Bchron')
install.packages('dplyr')
install.packages('here')
install.packages('magrittr')
install.packages('purrr')
install.packages('readr')
install.packages('readxl')
install.packages('rcarbon')
install.packages('tibble')
```

When baydem is installed, so is Rstan, which may have further depenencies. If so, see:

[https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started](https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started)

## Contents

* Input data files:
    + MesoRAD-v.1.2_no_locations.xlsx
    + Tikal_Demography.xlsx
* R files:
    + bayesian_radiocarbon_functions.R  
    + create_identif_results_exp.R  
    + create_identif_results_gm.R  
    + do_maya_inference.R  
    + do_sim_inference.R  
    + make_bayesian_radiocarbon_illustrations.R
* License and README files:
    + LICENSE.md
    + README.md
    + README.Rmd

# Running the analyses
## Simulation
If necessary, set the R working directory to the directory with the files (e.g., using setwd). Then type the following in R:

``` r
source('do_sim_inference.R')
```

This should take a few hours to finish. Once complete, the following ten files are created:  

* Fig1_sim_inference.pdf  
* sim_data.rds  
* sim_soln_100.rds  
* sim_soln_1000.rds  
* sim_soln_10000.rds  
* sim_anal_100.rds  
* sim_anal_1000.rds  
* sim_anal_10000.rds  
* sim_bc_100.rds  
* sim_bc_1000.rds  
* sim_bc_10000.rds  

Fig1_sim_inference.pdf is for Figure 1 in the article. sim_data.rds stores simulated samples. For N=100, N=1000, and N=10000, sim_soln\*, sim_anal\*, and sim_bc\* store, respectively, the results (samples) of Bayesian inference, analyses based on the Bayesian inference, and results of the BchronDensityFast fits.

## Maya results
If necessary, set the R working directory to the directory with the files (e.g., using setwd). Then type the following in R:

``` r
source('do_maya_inference.R')
```

This may take a day or more to finish. Once complete, the following new files are created:

* Mesorad files
    + log_mesorad_hygiene_counts.csv  
    + mesorad_filtered.csv  
    + log_mesorad_filtered_site_counts.csv  
    + mesorad_combined.csv  
    + mesorad_final.csv  
* Inference results
    + maya_inference_K2_tik.rds  
    + maya_inference_K4_tik.rds  
    + maya_inference_K6_tik.rds  
    + maya_inference_K8_tik.rds  
    + maya_inference_K10_tik.rds  
    + maya_inference_K2_all.rds  
    + maya_inference_K4_all.rds  
    + maya_inference_K6_all.rds  
    + maya_inference_K8_all.rds  
    + maya_inference_K10_all.rds  
* Figures and count data
    + Fig3_maya_inference_K10.pdf  
    + Fig4_tikal_prev_expert_comparison.pdf  
    + Fig5_maya_histograms.pdf  
    + FigS3_maya_inference_Kall.pdf  
    + FigS4_maya_inference_K2_and_K10_with_rc_curve.pdf  
    + supp_count_data.csv  

The first set of files provides the Mesorad data at various stages of processing. The second set of files (maya_inference_K) provides the inference results for Tikal/All sites with K=2 to 10 numbers of mixtures components. The third set of files is the figures and count data for the main manuscript and supplement.

## Identifiability results (supplement)
If necessary, set the R working directory to the directory with the files (e.g., using setwd). There are two scripts to run, one for the exponential example and one for the Gaussian mixture example. For the exponential example type:

``` r
source('create_identif_results_exp.R')
```

This should take only a few minutes to run. Once complete, the following new files are created:  

* FigS1_exp_example.pdf  
* SuppB_exp.csv  

FigS1_exp_example.pdf is Figure S1 in the supplement. SuppB_exp.csv provides summary information for the example, notably the mean measurement uncertainties reported in the supplement.

For the Gaussian mixture example type:

``` r
source('create_identif_results_gm.R')
```

This will take a few hours to run. Once complete, the following new file is created:  

* FigS2_gm_example.pdf  

FigS2_exp_example.pdf is Figure S2 in the supplement. Information about the identifiability checks is printed out in R as the script runs.

## Bayesian radiocarbon illustrations
If necessary, set the R working directory to the directory with the files (e.g., using setwd). Type:

``` r
source('make_bayesian_radiocarbon_illustrations.R')
```

This should take only a few seconds to run. Once complete, the following new file is created:  

* FigS1_exp_example.pdf  

Fig1_single_date_calibration.pdf is Figure 1 in the main text.
