source("create_Fig1.R")
source("create_identif_results_exp.R")
source("create_identif_results_gm.R")
source("do_simulations.R")
source("create_simulation_plots.R")
source("preprocess_mesorad_dataset.R")
source("do_tikal_inference.R")
source("create_tikal_plots.R")